spring.application.name=ProductionManager

# 1. Conexiunea la baza ta de date veche
spring.datasource.url=jdbc:mysql://localhost:3306/product_components?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

# 2. Userul si Parola extrase din JavaBean.java
spring.datasource.username=bdpi_app
spring.datasource.password=florian@2005

# 3. CRITIC: 'update' pastreaza datele vechi si doar se muleaza pe ele
spring.jpa.hibernate.ddl-auto=update

# Afisam SQL-ul pentru depanare
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect